### ISSUE TITLE
자료구조 문제

### ISSUE THREAD

**Issue by nErumin** [ZeroPage/CAUScheduler#14]
과제의 경우, 리스트 정보를 불러올 수 있는 작업과 상세 내역을 볼 수 있는 작업으로 나뉘어져 있습니다. 자료구조를 어떻게 설정해야할지 망설여집니다.

**Comment by WraithKim** [comment]
자료구조라는게 어떤 형태의 클래스로 저장할 지가 문제라는 거임?

**Comment by nErumin** [comment]
하나 클래스에 담자니 한 쪽에서는 쓰는데 다른 쪽에서는 못 쓰는 게 생길 수 있고, 두개 클래스로 나뉘자니 클래스 간 중복이 너무 많아서 문제고....

**Comment by nErumin** [comment]
정답.
2016. 1. 15. 오후 5:16에 "Donghwan Kim" <notifications@github.com>님이 작성:

**Comment by nErumin** [comment]
일단 추상클래스에서 분리시켜 해결했습니다.
