### ISSUE TITLE
해야할 일

### ISSUE THREAD

**Issue by WraithKim** [ZeroPage/CAUScheduler#2]
### 해결이 안 된 것
1. 구글 캘런더랑 연동을 시켜야 하는가...?
2. 과제 저장을 DB로 해야 하나...?
3. 과제를 누르면 과제에 대한 상세정보가 나와야 함
4. 과제를 과목, 제출 기한 등으로 필터링을 제공해야 하나?
5. 과제 알람 기능, 새 과제가 나오면 notification으로 알려줘야 함...?
# 
### 해결이 된 것
1. LoginActivity & 중대 포탈 계정으로 로그인
2. Drawer에 간략한 학생 정보, 로그아웃 표시 (design 폴더 참고...)
3. ~~SettingActivity~~PrefFragment

**Comment by WraithKim** [comment]
로그아웃 구현은 SharedPreference에서 계정 값을 빈 문자열("")로 바꾸면 된다네요...

**Comment by WraithKim** [comment]
알람 만들기 이전에 로그인 공사부터... Drawer 만들러 갑니다...
(~~MainActivity 브랜치에서 작업중: 튜토리얼 코드로 덮어놔서 개떡같습니다~~
 drawer 브랜치에서 작업중: 외국인이 적은 코드랑 한국인이 적은 코드랑 달라.....)
대부분의 공사가 완료되었습니다. 아마 지금 필요한 건 새 기능 추가될 때 마다 바로가기 더해주는 거???

**Comment by nErumin** [comment]
로그아웃 구현시에는 SharedPreference에서 저장값을 빈 문자열로 변경하고 LoginActivity로 이동시키는 것을 권장.
Preferences 키값은 R.string 참조

**Comment by WraithKim** [comment]
지금 포탈에서 받아올 수 있는 게 수강 강의 목록이랑 과제, 식단밖에 없다네요... 다른 것들은 구현할 수 있을지 없을 지...
그리고  과제는 리스트로 식단은 오늘 식단은 일단 텍스트로 줄줄 적어서 보여줄 것 같은데 회의를 더  해보고 결정...

**Comment by WraithKim** [comment]
드로어는 얼추 만들었으니 전 sqlite 좀 배우고 데이터 저장할 방법 좀 알아내 봅니다

**Comment by lyuha** [comment]
이것 다 하나하나 이슈로 만드는 걸 추천합니다. `#num` 형식으로 이슈 참고가 가능해집니다.
저런 리스트 형식은 [Mastering Markdown](https://guides.github.com/features/mastering-markdown)에 있는 Task lists를 이용하는 걸 추천합니다. 
- [x] Basic Syntax
- [ ] GFM

Task list로 처리한 일과 처리되지 않은 일이 구분이 안 된다면 `~~text~~` 로 감싸서 취소선을 만드는 방법도 있습니다.
- [x] ~~Basic Syntax~~
- [ ] GFM

**Comment by WraithKim** [comment]
@lyuha 체크박스가 가능한 건 오늘 알았네요. ㄳ

**Comment by WraithKim** [comment]
위의 분의 요청에 따라 여러 개의 이슈로 분리하겠습니다.
