### ISSUE TITLE
1/11에 시간 되나요...?

### ISSUE THREAD

**Issue by WraithKim** [ZeroPage/CAUScheduler#4]
모여서 얘기좀 합시다. 이제 뭘 해야 될지 좀 말좀 해봅시다. 카톡이든 뭐든 간에... 좀

**Comment by WraithKim** [comment]
젠장 망했다

**Comment by lyuha** [comment]
slack 멘션 기능을 더 적극 이용하거나 / 카톡으로 강하게 이야기 하거나 / @WraithKim github 멘션을 이용하는 것도 한 방법
