### ISSUE TITLE
에루밍님 부탁드릴게 있습니다.

### ISSUE THREAD

**Issue by OnAndOff-Game** [ZeroPage/CAUScheduler#5]
게임과학고등학교에서 게임관련 공부를 하고있는 재학생입니다.
에루밍님 프로젝트중에서 AILibrary라는 프로젝트에서 XmlItemReader.cs 부분에서 막혔습니다.
Xml을 사용해본적이 없어서 Elements()가 무엇인지도 몰라서 스키마를 어떻게 만들어야 할지 막막해요...
 가능하시다면 아이템관련 스키마좀 보여주실수 있을까요?

**Comment by WraithKim** [comment]
nerumin90@gmail.com
메일로 부탁합니다.
