### ISSUE TITLE
데이터 저장으로 SQLite 활용하기

### ISSUE THREAD

**Issue by WraithKim** [ZeroPage/CAUScheduler#7]
오프라인 상태에서도 마지막에 봤던 데이터를 열람할 수 있도록, 과제나 공지사항 등의 데이터를 저장하려고 합니다. 안드로이드에서 데이터를 저장하는 방법이 여러가지가 있는데 그 중에서 DB인 SQLite를 활용해볼까 생각 중입니다. 
테이블로 과제 테이블과, 수강과목 테이블, 공지사항 테이블, 식단 테이블이 필요할 것이라고 생각되며, 추가로 필요한 테이블은 여기에 코멘트로 알리겠습니다.
혹시 DB를 사용하는 게 적합하지 않는다 등의 의견이 있다면 여기에 코멘트를 남겨주세요.

**Comment by dunamu-keira** [comment]
이거 추천하고 갑니다
https://realm.io/kr/

**Comment by WraithKim** [comment]
@Rabierre 구글 IO Extends에서 봤던 것 같은데 확인해볼께요 (SQLite도 그저께 배워서 이게 가능할 지 모르겠습니다.)

**Comment by dunamu-keira** [comment]
어차피 다 처음이면 상관없지 않을까..! 안드 개발자가 그러는데 요즘 저게 엄청 핫하다고 강추했음ㅋㅋ

**Comment by lyuha** [comment]
iOS 용으로 쓰면 모르겠는데 아직, 안드로이드는 단말기 이슈들이 남아있는 상태입니다.
realm/realm-java#2071 를 보시면 정렬이 핸드폰마다 다르다고 합니다. 이런 이슈들이 있는 것을 감안하고 써야합니다.

장점은
1. 빠르다
2. 객체 모델을 쓸 수 있다
라고 합니다.

**Comment by tebica** [comment]
안녕하세요,
Realm에서 일하고 있는 개발자 입니다. 현재 Realm은 Google, Amazon, Pinterest, LINE, 네이버, CJ몰, 리디북스 등 많은에서 실제 쓰이고 있고요. Github와 StackOverflow를 통해 리포팅 된 버그 해결을 최우선 순위로 개발하고 있습니다.
참조하신 sorting 버그는 현재 저희쪽에서 재현이 되지 않고 있고, 이슈를 올린 쪽에서도 재현 할 수 있는 경로를 제시하지 못하고있네요. 많은 버그 이슈를 처리한 경험을 비추어보아 속단하기는 이르지만 잘못된 버그로 보입니다.
현재 안드로이드에서 디바이스 별 알려진 이슈는 없다고 할 수 있을 정도로 안정성은 걱정하지 않으셔도 될 것 같습니다. 추가로 궁금하신 부분이나 필요하신 부분은 한국어 이메일 kr@realm.io 이나 Github mention으로 알려주시면 빠른 답변 드리겠습니다.
감사합니다.

**Comment by WraithKim** [comment]
일단 Realm을 생각해보고 Contract부터 만들어 볼께요
dataModel 브랜치에서 작업 시작합니다.(사실 배운지 얼마 안되서 뭔지 모르겠다...)

**Comment by WraithKim** [comment]
Realm을 고민을 해봤는데 익숙하지도 않고, 제약사항을 고려해야 해서 힘드네요.  sqlite로 일단 만들고 나중에 속도 저하가 있으면 고려해볼께요...

**Comment by rino0601** [comment]
http://ormlite.com/sqlite_java_android_orm.shtml

무턱대고 ORMLite 추천. 
sqlite 날로 쓰면 일일히 스키마 만들어야 해서 매우 번거로워요
